import React from 'react'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

import '@/styles/globals.css'
import StoreProviders from '@/components/common/StoreProviders'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
    modal,
}: Readonly<{
    children: React.ReactNode
    modal: React.ReactNode
}>) {
    return (
        <StoreProviders>
            <html lang="en">
                <body className={inter.className}>{children}</body>
                {modal}
            </html>
        </StoreProviders>
    )
}
