import React from 'react'
import type { Metadata } from 'next'
import { Noto_Sans_TC } from 'next/font/google'

import { Footer } from '@/components/layout'
import StoreProviders from '@/components/common/StoreProviders'

import '@/styles/globals.css'

const noto_Sans_TC = Noto_Sans_TC({ subsets: ['latin'] })

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
    modal,
}: Readonly<{
    children: React.ReactNode
    modal: React.ReactNode
}>) {
    return (
        <StoreProviders>
            <html lang="en">
                <body className={noto_Sans_TC.className}>
                    {children}
                    <Footer />
                </body>
                {modal}
            </html>
        </StoreProviders>
    )
}
