export const COUNTRIES = [
    { label: '台北市', value: '0' },
    { label: '新北市', value: '1' },
    { label: '桃園市', value: '2' },
    { label: '台中市', value: '3' },
    { label: '台南市', value: '4' },
    { label: '高雄市', value: '5' },
]

export const THEATERS = [
    [
        { label: '信義威秀影城', value: '信義威秀影城' },
        { label: 'MUVIE CINEMAS松仁威秀', value: 'MUVIE CINEMAS松仁威秀' },
        { label: '誠品電影院', value: '誠品電影院' },
        { label: '京站威秀影城', value: '京站威秀影城' },
        { label: '國賓大戲院', value: '國賓大戲院' },
        { label: '獅子林新光影城', value: '獅子林新光影城' },
        { label: '今日秀泰影城', value: '今日秀泰影城' },
        { label: '喜滿客影城絕色店', value: '喜滿客影城絕色店' },
        { label: '光點華山電影館', value: '光點華山電影館' },
        { label: '長春國賓影城', value: '長春國賓影城' },
        { label: '欣欣秀泰影城', value: '欣欣秀泰影城' },
        { label: '光點台北', value: '光點台北' },
        { label: '美麗華大直影城', value: '美麗華大直影城' },
        { label: '美麗新大直皇家影城', value: '美麗新大直皇家影城' },
        { label: '天母新光影城', value: '天母新光影城' },
    ],
    [
        { label: '中和環球威秀影城', value: '中和環球威秀影城' },
        { label: '喜樂時代影城永和店', value: '喜樂時代影城永和店' },
        { label: '鴻金寶麻吉影城', value: '鴻金寶麻吉影城' },
        { label: '晶冠廣場國賓影城', value: '晶冠廣場國賓影城' },
        { label: '美麗新宏匯影城', value: '美麗新宏匯影城' },
        { label: '國家電影及視聽文化中心', value: '國家電影及視聽文化中心' },
        { label: '天台影城', value: '天台影城' },
        { label: '林口昕境國賓影城', value: '林口昕境國賓影城' },
        { label: '美麗新淡海影城', value: '美麗新淡海影城' },
        { label: '淡水禮萊國賓影城', value: '淡水禮萊國賓影城' },
        { label: '板橋大遠百威秀影城', value: '板橋大遠百威秀影城' },
        { label: '板橋秀泰影城', value: '板橋秀泰影城' },
        {
            label: '府中15新北市紀錄片放映院',
            value: '府中15新北市紀錄片放映院',
        },
        { label: '樹林秀泰影城', value: '樹林秀泰影城' },
        { label: '土城秀泰影城', value: '土城秀泰影城' },
        { label: '新店裕隆城威秀影城', value: '新店裕隆城威秀影城' },
        { label: '板橋林園電影城', value: '板橋林園電影城' },
    ],
    [
        { label: '統領威秀影城', value: '統領威秀影城' },
        { label: '站前in89統領影城', value: '站前in89統領影城' },
        { label: '八德置地國賓影城', value: '八德置地國賓影城' },
        { label: '美麗新台茂影城', value: '美麗新台茂影城' },
        { label: '青埔新光影城', value: '青埔新光影城' },
        { label: '喜樂時代影城A19店', value: '喜樂時代影城A19店' },
        { label: '威尼斯影城', value: '威尼斯影城' },
    ],
    [
        { label: '中港新光影城', value: '中港新光影城' },
        { label: '大遠百威秀影城', value: '大遠百威秀影城' },
        { label: 'TIGER CITY威秀影城', value: 'TIGER CITY威秀影城' },
        { label: '文心秀泰影城', value: '文心秀泰影城' },
        { label: '站前秀泰影城', value: '站前秀泰影城' },
        {
            label: '大魯閣新時代威秀影城',
            value: '大魯閣新時代威秀影城',
        },
        { label: '日日新影城', value: '日日新影城' },
        { label: '麗寶秀泰影城', value: '麗寶秀泰影城' },
    ],
    [
        { label: '大遠百威秀影城', value: '大遠百威秀影城' },
        { label: '南紡威秀影城', value: '南紡威秀影城' },
        { label: 'Focus威秀影城', value: 'Focus威秀影城' },
        { label: '西門新光影城', value: '西門新光影城' },
        { label: '仁德秀泰影城', value: '仁德秀泰影城' },
        { label: '國賓影城', value: '國賓影城' },
        { label: '南台影城', value: '南台影城' },
    ],
    [
        { label: '大遠百威秀影城', value: '大遠百威秀影城' },
        { label: 'SKM Park國賓影城', value: 'SKM Park國賓影城' },
        { label: '義大國賓影城', value: '義大國賓影城' },
        { label: '大立in89豪華影城', value: '大立in89豪華影城' },
        { label: '鹽埕in89駁二電影院', value: '鹽埕in89駁二電影院' },
        { label: '台鋁影城', value: '台鋁影城' },
        { label: '喜樂時代影城總圖店', value: '喜樂時代影城總圖店' },
        { label: '環球影城', value: '環球影城' },
        { label: '岡山秀泰影城', value: '岡山秀泰影城' },
        { label: '夢時代秀泰影城', value: '夢時代秀泰影城' },
        { label: '內惟藝術中心', value: '內惟藝術中心' },
        { label: '高雄市電影館', value: '高雄市電影館' },
    ],
]

export const MOVIES = [
    { label: '可憐的東西', value: '可憐的東西' },
    { label: '沙丘2', value: '沙丘2' },
    { label: '功夫熊貓', value: '功夫熊貓' },
    { label: '腦筋急轉彎2', value: '腦筋急轉彎2' },
    { label: '再見機器人', value: '再見機器人' },
]
