name: CI / CD

on:
  push:
    branches:
      - main
      - master
      - develope
  pull_request:
    branches:
      - main
      - master
      - develope
jobs:
  # ESlint Check
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'
      - name: Install dependencies
        run: npm install
      - name: Run ESLint
        run: npm run lint

  # Prettier Check
  prettier:
    runs-on: ubuntu-latest  
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install dependencies
        run: npm install  
      - name: Fix code style issues with Prettier
        run: npm run format
      - name: Run Prettier check
        run: npx prettier --check "**/*.tsx"
        